### ISSUE TITLE
Node sas binding OSX 64-bit 

### ISSUE THREAD

**Issue by AustinMCrane** [jerekshoe/redux-boilerplate#1]
ERROR in Missing binding /workspace/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

Found bindings for the following environments:
- OS X 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
 @ ./~/style-loader!./~/css-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js!./~/bootstrap-loader/no-op.js 4:14-164

ERROR in ./src/containers/App/style.scss
Module build failed: Error: Missing binding /workspace/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

Found bindings for the following environments:
- OS X 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (/workspace/node_modules/node-sass/lib/index.js:15:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/workspace/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at DependenciesBlock.loadPitch (/workspace/node_modules/webpack-core/lib/NormalModuleMixin.js:193:17)
    at DependenciesBlock.loadPitch (/workspace/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at DependenciesBlock.loadPitch (/workspace/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at DependenciesBlock.doBuild (/workspace/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (/workspace/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/workspace/node_modules/webpack/lib/Compilation.js:126:9)
    at Compilation.<anonymous> (/workspace/node_modules/webpack/lib/Compilation.js:398:8)
    at /workspace/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/workspace/node_modules/tapable/lib/Tapable.js:75:69)
    at onDoneResolving (/workspace/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/workspace/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
    at /workspace/node_modules/webpack/lib/NormalModuleFactory.js:98:13
    at /workspace/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /workspace/node_modules/webpack/node_modules/async/lib/async.js:52:16
 @ ./src/containers/App/index.js 13:0-23
Child extract-text-webpack-plugin:
        + 1 hidden modules

```
ERROR in Missing binding /workspace/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
```

**Comment by jerekshoe** [comment]
Error occurred because your Dockerfile copied the contents of node_modules when you installed them on your OS X environment. When node saw that you were trying to install them again on a different operating system, it issued this error
